// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletHub.Data;

#nullable disable

namespace WalletHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalletHub.Models.Categoria", b =>
                {
                    b.Property<string>("idCategoria")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("idUsuario")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("nombreCateg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipoCateg")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("idCategoria");

                    b.HasIndex("idUsuario");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            idCategoria = "CA001",
                            nombreCateg = "Hogar",
                            tipoCateg = "Gasto"
                        },
                        new
                        {
                            idCategoria = "CA002",
                            nombreCateg = "Alimentación",
                            tipoCateg = "Gasto"
                        },
                        new
                        {
                            idCategoria = "CA003",
                            nombreCateg = "Transporte",
                            tipoCateg = "Gasto"
                        },
                        new
                        {
                            idCategoria = "CA004",
                            nombreCateg = "Salud",
                            tipoCateg = "Gasto"
                        },
                        new
                        {
                            idCategoria = "CA005",
                            nombreCateg = "Educación",
                            tipoCateg = "Gasto"
                        },
                        new
                        {
                            idCategoria = "CA006",
                            nombreCateg = "Entretenimiento",
                            tipoCateg = "Gasto"
                        },
                        new
                        {
                            idCategoria = "CA007",
                            nombreCateg = "Salario",
                            tipoCateg = "Ingreso"
                        },
                        new
                        {
                            idCategoria = "CA008",
                            nombreCateg = "Emprendimiento Personal",
                            tipoCateg = "Ingreso"
                        },
                        new
                        {
                            idCategoria = "CA009",
                            nombreCateg = "Inversiones",
                            tipoCateg = "Ingreso"
                        },
                        new
                        {
                            idCategoria = "CA010",
                            nombreCateg = "Regalos",
                            tipoCateg = "Ingreso"
                        });
                });

            modelBuilder.Entity("WalletHub.Models.Reporte", b =>
                {
                    b.Property<string>("idReporte")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("fechaCreacionRepo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("finalPeriodo")
                        .HasColumnType("datetime2");

                    b.Property<string>("idUsuario")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("inicioPeriodo")
                        .HasColumnType("datetime2");

                    b.Property<string>("rutaArchivoRepo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("tipoArchivoRepo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idReporte");

                    b.HasIndex("idUsuario");

                    b.ToTable("Reporte", (string)null);
                });

            modelBuilder.Entity("WalletHub.Models.Transaccion", b =>
                {
                    b.Property<string>("idTransaccion")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("descripcionTransac")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("fechaTransac")
                        .HasColumnType("datetime2");

                    b.Property<string>("idCategoria")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("idUsuario")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("montoTransac")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idTransaccion");

                    b.HasIndex("idCategoria");

                    b.HasIndex("idUsuario");

                    b.ToTable("Transaccion", (string)null);
                });

            modelBuilder.Entity("WalletHub.Models.Usuario", b =>
                {
                    b.Property<string>("idUsuario")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("correoUsu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("nombreUsu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pwHashUsu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("WalletHub.Models.Categoria", b =>
                {
                    b.HasOne("WalletHub.Models.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WalletHub.Models.Reporte", b =>
                {
                    b.HasOne("WalletHub.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WalletHub.Models.Transaccion", b =>
                {
                    b.HasOne("WalletHub.Models.Categoria", "Categoria")
                        .WithMany("Transacciones")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WalletHub.Models.Usuario", "Usuario")
                        .WithMany("Transacciones")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WalletHub.Models.Categoria", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("WalletHub.Models.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Reportes");

                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
